# Generated by Django 2.2.12 on 2020-11-01 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wanteat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='shortcomment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食'),
        ),
        migrations.AddField(
            model_name='shortcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='foodrevert',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodComment', verbose_name='所属评论'),
        ),
        migrations.AddField(
            model_name='foodrevert',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='foodrevert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='foodmark',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食'),
        ),
        migrations.AddField(
            model_name='foodmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='discuss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Discuss', verbose_name='所属讨论'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='flavour',
            field=models.ManyToManyField(to='food.Flavour', verbose_name='美食的味道'),
        ),
        migrations.AddField(
            model_name='food',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='所属学校'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='该美食的作者'),
        ),
        migrations.AddField(
            model_name='eated',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食'),
        ),
        migrations.AddField(
            model_name='eated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
