# Generated by Django 2.2.12 on 2020-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200726_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='vote_score',
            new_name='all_score',
        ),
        migrations.AddField(
            model_name='food',
            name='score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='评分'),
        ),
    ]
