# Generated by Django 2.2.12 on 2020-07-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_auto_20200726_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='打分分数')),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='添加时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食')),
                ('short_commnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ShortComment', verbose_name='打分短评')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
