# Generated by Django 2.2.12 on 2020-07-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_eatrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EatRecord',
        ),
    ]
