# Generated by Django 2.2.12 on 2020-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200726_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='revert_number',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
    ]
