# Generated by Django 2.2.12 on 2020-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_foodcomment_revert_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='address_image',
            field=models.URLField(default='', verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_fifth',
            field=models.URLField(default='', verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_first',
            field=models.URLField(verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_fourth',
            field=models.URLField(default='', verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_second',
            field=models.URLField(default='', verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_third',
            field=models.URLField(default='', verbose_name='图片url'),
        ),
    ]
