# Generated by Django 2.2.12 on 2020-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_foodmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmark',
            name='score',
            field=models.IntegerField(default=1, verbose_name='打分的记录'),
        ),
    ]
