# Generated by Django 2.2.12 on 2020-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodmark_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='short_comment_number',
            field=models.IntegerField(default=0, verbose_name='短评数'),
        ),
    ]
