# Generated by Django 2.2.12 on 2020-07-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_food_discuss_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='讨论内容'),
        ),
    ]
