# Generated by Django 2.2.12 on 2020-07-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20200728_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='内容'),
        ),
    ]
