# Generated by Django 2.2.12 on 2020-07-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20200728_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='内容'),
        ),
    ]
