# Generated by Django 2.2.12 on 2020-07-31 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0019_auto_20200728_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discuss',
            options={'verbose_name': '讨论', 'verbose_name_plural': '讨论'},
        ),
        migrations.AlterModelOptions(
            name='flavour',
            options={'verbose_name': '味道', 'verbose_name_plural': '味道'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '美食', 'verbose_name_plural': '美食'},
        ),
        migrations.AlterModelOptions(
            name='foodcomment',
            options={'verbose_name': '讨论评论', 'verbose_name_plural': '讨论评论'},
        ),
        migrations.AlterModelOptions(
            name='foodmark',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterModelOptions(
            name='foodrevert',
            options={'verbose_name': '讨论回复', 'verbose_name_plural': '讨论回复'},
        ),
        migrations.AlterModelOptions(
            name='shortcomment',
            options={'verbose_name': '短评', 'verbose_name_plural': '短评'},
        ),
        migrations.CreateModel(
            name='WantEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '想吃记录',
                'verbose_name_plural': '想吃记录',
            },
        ),
        migrations.CreateModel(
            name='Eated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='所属美食')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '吃过记录',
                'verbose_name_plural': '吃过记录',
            },
        ),
    ]
