# Generated by Django 2.2.12 on 2020-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20200731_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='address_image',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_fifth',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_first',
            field=models.URLField(max_length=300, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_fourth',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_second',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_third',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
    ]
