# Generated by Django 2.2.12 on 2020-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default='headimage/default.png', upload_to='headimage/'),
        ),
    ]
