# Generated by Django 2.2.12 on 2020-07-12 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200711_1456'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='collect_number',
            field=models.IntegerField(default=0, verbose_name='被收藏总数'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='被喜欢总数'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='read_number',
            field=models.IntegerField(default=0, verbose_name='被阅读总数'),
        ),
        migrations.CreateModel(
            name='UserDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '赞同回答'), (1, '收藏回答'), (2, '回答问题'), (3, '关注问题'), (4, '提出问题')], verbose_name='操作类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('answer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
