# Generated by Django 2.2.12 on 2020-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_head_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='we_chat_openid',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='微信openid'),
        ),
    ]
