# Generated by Django 2.2.12 on 2020-07-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200712_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdynamic',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
