# Generated by Django 2.2.12 on 2020-11-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201103_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校'),
        ),
    ]
