# Generated by Django 2.2.12 on 2020-05-29 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200529_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_target_user', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
    ]
