# Generated by Django 2.2.12 on 2020-06-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myattention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='mycomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myquestion',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='myquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyAnswer',
        ),
        migrations.DeleteModel(
            name='MyComment',
        ),
        migrations.DeleteModel(
            name='MyQuestion',
        ),
    ]
