# Generated by Django 2.2.12 on 2020-06-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200602_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='banzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.banji')),
            ],
        ),
        migrations.DeleteModel(
            name='MyCollect',
        ),
    ]
