# Generated by Django 2.2.12 on 2020-06-02 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20200531_1551'),
        ('user', '0006_auto_20200602_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banzhang',
            name='banji',
        ),
        migrations.AddField(
            model_name='user',
            name='answer_collect',
            field=models.ManyToManyField(related_name='answer_collect', to='question.Answer', verbose_name='用户回答收藏'),
        ),
        migrations.AddField(
            model_name='user',
            name='attention',
            field=models.ManyToManyField(related_name='_user_attention_+', to=settings.AUTH_USER_MODEL, verbose_name='用户关注'),
        ),
        migrations.AddField(
            model_name='user',
            name='question_collect',
            field=models.ManyToManyField(related_name='question_collect', to='question.Question', verbose_name='用户问题收藏'),
        ),
        migrations.DeleteModel(
            name='banji',
        ),
        migrations.DeleteModel(
            name='banzhang',
        ),
    ]
