# Generated by Django 2.2.12 on 2020-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userdynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='add_time',
            field=models.FloatField(verbose_name='动态的创作时间的时间戳'),
        ),
    ]
