# Generated by Django 2.2.12 on 2020-06-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200602_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAttention',
        ),
    ]
