# Generated by Django 2.2.12 on 2020-07-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200719_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Answer'),
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
