# Generated by Django 2.2.12 on 2020-07-20 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200720_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Answer'),
        ),
    ]
