# Generated by Django 2.2.12 on 2020-06-05 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200602_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AlterField(
            model_name='user',
            name='answer_collect',
            field=models.ManyToManyField(null=True, related_name='answer_collect', to='question.Answer', verbose_name='用户回答收藏'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attention',
            field=models.ManyToManyField(null=True, related_name='_user_attention_+', to=settings.AUTH_USER_MODEL, verbose_name='用户关注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Campus', verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.College', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Grade', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(null=True, to='user.Interest', verbose_name='用户兴趣'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='question_collect',
            field=models.ManyToManyField(null=True, related_name='question_collect', to='question.Question', verbose_name='用户问题收藏'),
        ),
    ]
