# Generated by Django 2.2.12 on 2020-06-12 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200605_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_collect',
            field=models.ManyToManyField(related_name='answer_collect', to='question.Answer', verbose_name='用户回答收藏'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attention',
            field=models.ManyToManyField(related_name='_user_attention_+', to=settings.AUTH_USER_MODEL, verbose_name='用户关注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='user.Interest', verbose_name='用户兴趣'),
        ),
        migrations.AlterField(
            model_name='user',
            name='question_collect',
            field=models.ManyToManyField(related_name='question_collect', to='question.Question', verbose_name='用户问题收藏'),
        ),
    ]
