# Generated by Django 2.2.12 on 2020-07-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200720_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='comment_number',
            field=models.IntegerField(default=0, verbose_name='被评论数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='手机号码'),
        ),
    ]
