# Generated by Django 2.2.12 on 2020-07-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200722_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='add_time',
            field=models.FloatField(db_index=True, verbose_name='动态的创作时间的时间戳'),
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='type',
            field=models.IntegerField(choices=[(0, '赞同回答'), (1, '收藏回答'), (2, '回答问题'), (3, '关注问题'), (4, '提出问题')], db_index=True, verbose_name='操作类型'),
        ),
    ]
