# Generated by Django 2.2.12 on 2020-06-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200612_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentBrowseQuestion',
        ),
    ]
