# Generated by Django 2.2.12 on 2020-07-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200725_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campus',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
