# Generated by Django 2.2.12 on 2020-07-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200726_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': '兴趣', 'verbose_name_plural': '兴趣'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': '用户创作数据', 'verbose_name_plural': '用户创作数据'},
        ),
        migrations.AlterModelOptions(
            name='userdynamic',
            options={'verbose_name': '用户动态', 'verbose_name_plural': '用户动态'},
        ),
    ]
