# Generated by Django 2.2.12 on 2020-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200731_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_campus',
            field=models.IntegerField(choices=[(0, '不是校区'), (1, '是校区')], default=0, verbose_name='是否是一个校区'),
        ),
    ]
