# Generated by Django 2.2.12 on 2020-09-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='学校名'),
        ),
    ]
