# Generated by Django 2.2.12 on 2020-09-11 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20200909_0917'),
        ('user', '0018_usercollectfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='question_collect',
        ),
        migrations.AlterField(
            model_name='usercollectfood',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='添加时间'),
        ),
        migrations.CreateModel(
            name='UserCollectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='添加时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='所属问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
