# Generated by Django 2.2.12 on 2020-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200911_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_portrait',
            field=models.URLField(default='', max_length=300, verbose_name='图片url'),
        ),
    ]
