# Generated by Django 2.2.12 on 2020-10-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20201004_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': '兴趣信息', 'verbose_name_plural': '兴趣信息'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校信息', 'verbose_name_plural': '学校信息'},
        ),
        migrations.AlterModelOptions(
            name='usercollectfood',
            options={'verbose_name': '用户收藏的美食', 'verbose_name_plural': '用户收藏的美食'},
        ),
        migrations.AlterModelOptions(
            name='usercollectquestion',
            options={'verbose_name': '用户收藏的问题', 'verbose_name_plural': '用户收藏的问题'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': '用户创作者数据', 'verbose_name_plural': '用户创作者数据'},
        ),
    ]
