# Generated by Django 2.2.12 on 2020-10-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20201005_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校'),
        ),
    ]
