# Generated by Django 2.2.12 on 2020-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymity', models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='是否匿名')),
                ('content', models.TextField(default='', max_length=100000, verbose_name='用户回答')),
                ('abstract', models.CharField(default='', max_length=18, verbose_name='草稿摘要')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '回答草稿',
                'verbose_name_plural': '回答草稿',
            },
        ),
        migrations.CreateModel(
            name='FoodDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='美食名称')),
                ('image_first', models.URLField(null=True, verbose_name='图片url')),
                ('image_second', models.URLField(null=True, verbose_name='图片url')),
                ('image_third', models.URLField(null=True, verbose_name='图片url')),
                ('image_fourth', models.URLField(null=True, verbose_name='图片url')),
                ('image_fifth', models.URLField(null=True, verbose_name='图片url')),
                ('address_image', models.URLField(null=True, verbose_name='图片url')),
                ('desc', models.CharField(max_length=150, null=True, verbose_name='美食简短描述')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='美食地址')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=40, verbose_name='地点的经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=40, verbose_name='地点的维度')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '美食草稿',
                'verbose_name_plural': '美食草稿',
            },
        ),
    ]
