# Generated by Django 2.2.12 on 2020-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddraft',
            name='flavour',
            field=models.ManyToManyField(to='food.Flavour', verbose_name='美食的味道'),
        ),
    ]
