# Generated by Django 2.2.12 on 2020-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdraft',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
    ]
