# Generated by Django 2.2.12 on 2020-08-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200814_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddraft',
            name='image_fifth',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='image_fourth',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='image_third',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
    ]
