# Generated by Django 2.2.12 on 2020-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20200814_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddraft',
            name='address_image',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='image_first',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='image_second',
            field=models.URLField(null=True, verbose_name='图片url'),
        ),
    ]
