# Generated by Django 2.2.12 on 2020-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20200814_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddraft',
            name='desc',
            field=models.CharField(max_length=150, null=True, verbose_name='美食简短描述'),
        ),
    ]
