# Generated by Django 2.2.12 on 2020-08-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20200814_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddraft',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=40, verbose_name='地点的维度'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=40, verbose_name='地点的经度'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='name',
            field=models.CharField(max_length=20, verbose_name='美食名称'),
        ),
    ]
