# Generated by Django 2.2.12 on 2020-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_auto_20200814_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddraft',
            name='address',
            field=models.CharField(db_index=True, max_length=50, verbose_name='美食地址'),
        ),
        migrations.AlterField(
            model_name='fooddraft',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='美食名称'),
        ),
    ]
