# Generated by Django 2.2.12 on 2020-07-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200719_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymity',
            field=models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='是否匿名'),
        ),
        migrations.AddField(
            model_name='revert',
            name='is_anonymity',
            field=models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='是否匿名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approval_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='获赞数'),
        ),
    ]
