# Generated by Django 2.2.12 on 2020-05-18 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200517_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='内容修改时间'),
        ),
        migrations.CreateModel(
            name='HotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacn_number_24hour', models.IntegerField(default=0, verbose_name='24小时浏览量')),
                ('answer_number_24hour', models.IntegerField(default=0, verbose_name='24小时回答量')),
                ('attention_number_24hour', models.IntegerField(default=0, verbose_name='24小时关注量')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问题id')),
            ],
        ),
        migrations.CreateModel(
            name='AllRecentScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '浏览'), (1, '回答'), (2, '关注')], verbose_name='操作类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问题id')),
            ],
        ),
    ]
