# Generated by Django 2.2.12 on 2020-07-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200722_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revert',
            old_name='is_anonymity',
            new_name='is_target_user_anonymity',
        ),
        migrations.AddField(
            model_name='revert',
            name='is_user_anonymity',
            field=models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='是否匿名'),
        ),
    ]
