# Generated by Django 2.2.12 on 2020-05-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200520_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Answer', verbose_name='所属回答'),
        ),
    ]
