# Generated by Django 2.2.12 on 2020-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200722_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default='', max_length=100000, verbose_name='用户回答'),
        ),
    ]
