# Generated by Django 2.2.12 on 2020-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200726_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.IntegerField(choices=[(0, '问题'), (1, '回答')], db_index=True, default=0),
        ),
    ]
