# Generated by Django 2.2.12 on 2020-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20200731_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anonymity',
            field=models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='是否匿名'),
        ),
        migrations.AlterField(
            model_name='revert',
            name='is_user_anonymity',
            field=models.IntegerField(choices=[(0, '不匿名'), (1, '匿名')], default=0, verbose_name='用户是否匿名'),
        ),
    ]
