# Generated by Django 2.2.12 on 2020-05-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20200528_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotquestionsevendags',
            name='answer_number',
        ),
        migrations.RemoveField(
            model_name='hotquestionsevendags',
            name='attention_number',
        ),
        migrations.RemoveField(
            model_name='hotquestionsevendags',
            name='collect_number',
        ),
        migrations.RemoveField(
            model_name='hotquestionsevendags',
            name='comment_number',
        ),
        migrations.RemoveField(
            model_name='hotquestionsevendags',
            name='sacn_number',
        ),
        migrations.RemoveField(
            model_name='hotquestiontwentyfouryhours',
            name='answer_number',
        ),
        migrations.RemoveField(
            model_name='hotquestiontwentyfouryhours',
            name='attention_number',
        ),
        migrations.RemoveField(
            model_name='hotquestiontwentyfouryhours',
            name='collect_number',
        ),
        migrations.RemoveField(
            model_name='hotquestiontwentyfouryhours',
            name='comment_number',
        ),
        migrations.RemoveField(
            model_name='hotquestiontwentyfouryhours',
            name='sacn_number',
        ),
        migrations.AlterField(
            model_name='hotquestionsevendags',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='问题分数'),
        ),
        migrations.AlterField(
            model_name='hotquestiontwentyfouryhours',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='问题分数'),
        ),
        migrations.CreateModel(
            name='HotQuestionTwentyFouryHoursOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacn_number', models.IntegerField(default=0, verbose_name='过去24小时浏览量')),
                ('answer_number', models.IntegerField(default=0, verbose_name='过去24小时回答量')),
                ('attention_number', models.IntegerField(default=0, verbose_name='过去24小时关注量')),
                ('collect_number', models.IntegerField(default=0, verbose_name='过去24小时收藏量')),
                ('comment_number', models.IntegerField(default=0, verbose_name='过去24小时评论量')),
                ('score', models.FloatField(default=0.0, verbose_name='热度值')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问题id')),
            ],
        ),
        migrations.CreateModel(
            name='HotQuestionSevenDagsOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacn_number', models.IntegerField(default=0, verbose_name='过去7天浏览量')),
                ('answer_number', models.IntegerField(default=0, verbose_name='过去7天回答量')),
                ('attention_number', models.IntegerField(default=0, verbose_name='过去7天关注量')),
                ('collect_number', models.IntegerField(default=0, verbose_name='过去7天收藏量')),
                ('comment_number', models.IntegerField(default=0, verbose_name='过去7天评论量')),
                ('score', models.FloatField(default=0.0, verbose_name='热度值')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问题id')),
            ],
        ),
        migrations.CreateModel(
            name='HotQuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_on_hotquestion_time', models.DateField(verbose_name='上次上榜时间')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问题id')),
            ],
        ),
    ]
