# Generated by Django 2.2.12 on 2020-07-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200731_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '回答', 'verbose_name_plural': '回答'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterModelOptions(
            name='revert',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
    ]
