# Generated by Django 2.2.12 on 2020-08-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20200731_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='所属学校'),
        ),
    ]
