# Generated by Django 2.2.12 on 2020-09-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20200814_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='abstract',
            field=models.CharField(default='', max_length=100, verbose_name='回答摘要'),
        ),
        migrations.AddField(
            model_name='answer',
            name='first_image',
            field=models.URLField(null=True, verbose_name='回答第一张图片'),
        ),
    ]
