# Generated by Django 2.2.12 on 2020-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20200909_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='first_image',
            field=models.URLField(max_length=300, null=True, verbose_name='回答第一张图片'),
        ),
    ]
