# Generated by Django 2.2.12 on 2020-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_myattention'),
        ('question', '0014_auto_20200531_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interest_circle',
            field=models.ManyToManyField(related_name='interest_circle', to='user.Interest', verbose_name='问题的兴趣圈子'),
        ),
        migrations.DeleteModel(
            name='InterertCircle',
        ),
    ]
