# Generated by Django 2.2.12 on 2020-06-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20200602_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotquestionrecord',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='hotquestionsevendags',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='hotquestionsevendagsoperation',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='hotquestiontwentyfouryhours',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='hotquestiontwentyfouryhoursoperation',
            old_name='question_id',
            new_name='question',
        ),
    ]
