# Generated by Django 2.2.12 on 2020-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20200602_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_number',
            field=models.IntegerField(default=0, verbose_name='回答总数'),
        ),
    ]
