# Generated by Django 2.2.12 on 2020-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_question_answer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment_number',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
