# Generated by Django 2.2.12 on 2020-06-12 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0019_auto_20200603_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revert',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revert_target_user', to=settings.AUTH_USER_MODEL, verbose_name='被回复的人'),
        ),
        migrations.AlterField(
            model_name='revert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revert_comment_user', to=settings.AUTH_USER_MODEL, verbose_name='所属的用户'),
        ),
        migrations.CreateModel(
            name='AttentionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_target_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
