# Generated by Django 2.2.12 on 2020-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20200612_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote_number',
            field=models.IntegerField(default=0, verbose_name='投票总数'),
        ),
        migrations.AddField(
            model_name='revert',
            name='vote_number',
            field=models.IntegerField(default=0, verbose_name='投票总数'),
        ),
    ]
